export enum SocketEvent {
  SyncState = 'sync_state',
  PlayerReconnected = 'player_reconnected',
  JoinRoom = 'joined_room',
  CreateRoom = 'created_room',
  RedirectPlayers = 'redirect_players',
  Redirect = 'redirect',
  CreateGame = 'created_game',
  AssignPieceType = 'assigned_piece_type',
  SelectActivePlayer = 'select_active_player',
  SetActivePlayer = 'set_active_player',
  UpdateGame = 'updated_game',
  IncrementCountTurn = 'increment_count_turn',
  ChangeActiveStatus = 'change_active_status',
  DecrementPieceCount = 'decrement_piece_count',
  ResetGame = 'reset_game',
  ShuffleField = 'shuffle_field',
  LeaveRoom = 'leaved_room',
}
