export enum SocketEvent {
  Connect = "connect",
  Disconnect = "disconnect",
  SyncState = "sync_state",
  PlayerReconnected = "player_reconnected",
  Error = "connect_error",
  JoinRoom = "joined_room",
  CreateRoom = "created_room",
  Redirect = "redirect",
  CreateGame = "created_game",
  AssignPieceType = "assigned_piece_type",
  SelectActivePlayer = "select_active_player",
  SetActivePlayer = "set_active_player",
  UpdateGame = "updated_game",
  IncrementCountTurn = "increment_count_turn",
  ChangeActiveStatus = "change_active_status",
  DecrementPieceCount = "decrement_piece_count",
  ResetGame = "reset_game",
  ShuffleField = "shuffle_field",
  LeaveRoom = "leaved_room",
  RedirectPlayers = "redirect_players",
  MakeMove = "make_move",
  StartGame = "start_game",
  PlayAgain = "play_again",
  AssignWinner = "assign_winner",
}
